### PR TITLE
Fixed action buttons in grid

### PR DESCRIPTION
**Pull request by Ruslan-Aleev**
Fixed action buttons in grid:
- Added attributes and specified `target="_blank"` for the view and edit buttons. I also set it for the edit button, because otherwise the meaning of the grid is lost if you fall inside while editing (but that's up for discussion).
- Added translation to title.

before

after

### CODE REVIEW

**Comment by theboxer** [comment]
@Ruslan-Aleev The grid is not lost, if you want to open the view/edit in new tab, the common pattern is to `cmd/ctrl` click the link. Forcing links to always open in new tab is IMHO bad behaviour.

If you can remove those attributes, I'll happily merge the lexicon fix.

**Comment by Ruslan-Aleev** [comment]
@theboxer Still, I am in favor of leaving open tabs in a new window for the "View" button, since that is how it works within MODX.

view_action

**Comment by theboxer** [comment]
@Ruslan-Aleev fair point, so keep it on view and remove it from edit.

**Comment by Ruslan-Aleev** [comment]
@theboxer PR corrected, check

**Comment by theboxer** [comment]
Thank you!

**Pull request merged**
