### PR TITLE
Html tag correction and Italian Translation

### PR DESCRIPTION
**Pull request by FerX**
I found a little error html tags in all translations and complete Italian translation.

### CODE REVIEW

**Comment by theboxer** [comment]
Thank you for the update, I had to change it in source lexicon and run it through crowdin where are all translations.

**Comment by FerX** [comment]
And the italian translation ?
Thanks

**Comment by theboxer** [comment]
The change is in all lexicons, you can check change log here: https://github.com/modxcms/Collections/commit/16dec0ae4e1214c2bc7ce68027e1a9cb987118d7

**Comment by FerX** [comment]
but I put the translations in Italian that are missing and there are no commit

**Comment by theboxer** [comment]
Sorry, I missed you included translations, anyway, I can't merge translations through github. All translations must go through https://crowdin.com/project/collections

I'd be grateful if you can do all Italian lexicon changes there.

**Pull request closed without merging**
